export const IFs = [
  "IFAC",
  "IFAL",
  "IFAP",
  "IFAM",
  "IFBA",
  "IFCE",
  "IFB",
  "IFES",
  "IFG",
  "IFMA",
  "IFMT",
  "IFMS",
  "IFMG",
  "IFPA",
  "IFPB",
  "IFPR",
  "IFPE",
  "IFPI",
  "IFRJ",
  "IFRN",
  "IFRS",
  "IFRO",
  "IFRR",
  "IFSC",
  "IFSP",
  "IFS",
  "IFTO",
];

export const CURSOs: Record<string, string[]> = {
  IFTO: [
    "Agronomia",
    "Educação Física",
    "Engenharia Civil",
    "Engenharia Elétrica",
    "Física",
    "Gestão do Agronegócio",
    "Gestão do Agronegócio (UAB/IFTO)",
    "Gestão de Turismo",
    "Gestão Pública",
    "Letras - Língua Portuguesa",
    "Matemática",
    "Pedagogia e EPT (UAB/IFTO)",
    "Sistemas para Internet",
    "Técnico em Administração",
    "Técnico em Agrimensura",
    "Técnico em Agronegócio",
    "Técnico em Automação Industrial",
    "Técnico em Controle Ambiental",
    "Técnico em Edificações",
    "Técnico em Eletrotécnica",
    "Técnico em Eventos",
    "Técnico em Informática",
    "Técnico em Informática para Internet",
    "Técnico em Mecatrônica",
    "Técnico em Secretariado",
    "Técnico em Segurança do Trabalho",
    "Zootecnia",
  ],
};
